apiVersion: v2.edp.epam.com/v1
kind: AdminConsole
metadata:
  name: edp-admin-console
spec:
  {{- if .Values.adminConsole.basePath }}
  basePath: "{{ .Values.adminConsole.basePath }}"
  {{- end }}
  edpSpec:
    name: {{ .Values.global.edpName }}
    dnsWildcard: {{ .Values.global.dnsWildCard }}
    testReportTools: "Allure"
  dbSpec:
    enabled: false
  keycloakSpec:
    enabled: {{ .Values.adminConsole.authKeycloakEnabled }}
