apiVersion: v2.edp.epam.com/v1alpha1
kind: AdminConsole
metadata:
  name: edp-admin-console
spec:
  basePath: {{.Values.adminConsole.basePath}}
  image: {{.Values.adminConsole.image}}
  {{- if .Values.adminConsole.imagePullSecrets}}
  imagePullSecrets:
    {{- range .Values.adminConsole.imagePullSecrets }}
    - {{. -}}
    {{- end -}}
  {{end}}
  version: {{.Values.adminConsole.version}}
  edpSpec:
    name: {{ .Values.global.edpName }}
    dnsWildcard: {{ .Values.global.dnsWildCard }}
    version: {{.Values.global.version}}
   {{- if eq .Values.global.platform "openshift" }}
    integrationStrategies: "Create,Clone,Import"
   {{- else }}
    integrationStrategies: "Import"
   {{- end }}
  dbSpec:
    enabled: {{ .Values.global.database.deploy }}
    name: {{ .Values.global.database.name }}
    hostname: {{ if .Values.global.database.host }}{{ .Values.global.database.host }}{{else}}"edp-install-wizard-db.{{.Values.global.edpName}}"{{end}}
    port: "{{ .Values.global.database.port }}"
  keycloakSpec:
    enabled: {{ .Values.adminConsole.authKeycloakEnabled }}