apiVersion: v2.edp.epam.com/v1alpha1
kind: AdminConsole
metadata:
  name: edp-admin-console
spec:
  basePath: "{{.Values.adminConsole.basePath}}"
  image: {{.Values.adminConsole.image}}
  {{- if .Values.adminConsole.imagePullSecrets}}
  imagePullSecrets:
    {{- range .Values.adminConsole.imagePullSecrets }}
    - {{. -}}
    {{- end -}}
  {{end}}
  version: {{.Values.adminConsole.version}}
  edpSpec:
    name: {{ .Values.global.edpName }}
    dnsWildcard: {{ .Values.global.dnsWildCard }}
    version: {{.Values.global.version}}
    integrationStrategies: "Create,Clone,Import"
    testReportTools: "Allure"
  dbSpec:
    enabled: {{ .Values.global.database.deploy }}
    name: {{ .Values.global.database.name }}
    hostname: {{ if .Values.global.database.host }}{{ .Values.global.database.host }}{{else}}"edp-db.{{.Values.global.edpName}}"{{end}}
    port: "{{ .Values.global.database.port }}"
  keycloakSpec:
    enabled: {{ .Values.adminConsole.authKeycloakEnabled }}