{{- if .Values.global.e2e.testing.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.global.database.name}}
spec:
  selector:
    matchLabels:
      app: {{.Values.global.database.name}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{.Values.global.database.name}}
    spec:
      containers:
        - env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: super-admin-db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: super-admin-db
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POSTGRES_DB
              value: {{.Values.global.database.name}}
          image: postgres:9.6
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready --host $POD_IP -U postgres -d postgres
            failureThreshold: 5
            initialDelaySeconds: 20
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
          name: {{.Values.global.database.name}}
          ports:
            - containerPort: {{.Values.global.database.port}}
              name: db
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready --host $POD_IP -U postgres -d postgres
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{.Values.global.database.name}}
      securityContext:
        runAsUser: 999
        runAsNonRoot: true
        fsGroup: 999
      serviceAccountName: edp-db
      volumes:
        - name: {{.Values.global.database.name}}
          persistentVolumeClaim:
            claimName: {{.Values.global.database.name}}
{{end}}