{{- if .Values.global.e2e.testing.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.global.database.name}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp2
  volumeMode: Filesystem
{{end}}