apiVersion: v1
kind: Service
metadata:
  name: {NAME}
spec:
  selector:
    app: vcluster
    release: {RELEASE_SELECTOR}
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  type: NodePort