apiVersion: v2
description: A Helm chart for EDP Admin Console Operator
home: https://epam.github.io/edp-install/
name: admin-console-operator
type: application
version: 2.12.0-SNAPSHOT
appVersion: 2.12.0-SNAPSHOT
icon: https://epam.github.io/edp-install/assets/logo.png
keywords:
  - edp
  - admin
  - console
  - pipelines
maintainers:
  - name: epmd-edp
    email: SupportEPMD-EDP@epam.com
    url: https://solutionshub.epam.com/solution/epam-delivery-platform
  - name: sergk
    url: https://github.com/SergK
sources:
  - https://github.com/epam/edp-admin-console
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/images: |
    - name: admin-console-operator:2.11.0
      image: epamedp/admin-console-operator:2.11.0
    - name: admin-console:2.12.0
      image: epamedp/edp-admin-console:2.12.0
    - name: postgres:9.6
      image: postgres:9.6
    - name: alpine:3.16.2
      image: alpine:3.16.2
  artifacthub.io/operatorCapabilities: Full Lifecycle
  artifacthub.io/crds: |
    - kind: AdminConsole
      version: v2.edp.epam.com/v1
      name: adminconsole
      displayName: AdminConsole
      description: AdminConsole configuration for Epam Delivery Platform
  artifacthub.io/crdsExamples: |
    - apiVersion: v2.edp.epam.com/v1
      kind: AdminConsole
      metadata:
        name: edp-admin-console
      spec:
        dbSpec:
          enabled: true
          hostname: edp-db
          name: edp-db
          port: '5432'
        edpSpec:
          dnsWildcard: example.com
          name: edp-dev
          testReportTools: Allure
        keycloakSpec:
          enabled: true
  artifacthub.io/links: |
    - name: EDP Documentation
      url: https://epam.github.io/edp-install/
    - name: EPAM SolutionHub
      url: https://solutionshub.epam.com/solution/epam-delivery-platform
