global:
  edpName: "edp"
  platform: "openshift"
  dnsWildCard:
  version: "v2.5.0"
  database:
    deploy: true
    host:
    name: "edp-install-wizard-db"
    port: 5432
  webConsole:
    url:


name: admin-console-operator
image:
  name: epamedp/admin-console-operator
  version: v2.5.4

adminConsole:
  image: "epamedp/edp-admin-console"
  version: "2.5.5"
  basePath: ""
  imagePullSecrets:
  authKeycloakEnabled: true