global:
  edpName: ""
  platform: "openshift"
  dnsWildCard:
  version: "2.8.2"
  database:
    deploy: true
    host:
    name: "edp-db"
    port: 5432
  webConsole:
    url:
  openshift:
    deploymentType: "deploymentConfigs"

name: admin-console-operator
image:
  name: epamedp/admin-console-operator
  # if not defined then .Chart.AppVersion is used
  version:
annotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

resources:
  limits:
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi

adminConsole:
  image: "epamedp/edp-admin-console"
  version: "2.8.1"
  basePath: ""
  imagePullSecrets:
  authKeycloakEnabled: true
  projectUrlMask: "/console/project/{namespace}/overview"
  imageStreamUrlMask: "/console/project/{namespace}/browse/images/{stream}"
  buildTools: "maven"
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ingress:
    annotations: {}

  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi
