global:
  edpName: ""
  platform: "openshift"
  dnsWildCard:
  version: "2.12.0-SNAPSHOT"
  database:
    deploy: true
    host: "edp-db"
    name: "edp-db"
    port: 5432
    image: "postgres:9.6"
    imagePullPolicy: "IfNotPresent"
  webConsole:
    url:
  openshift:
    deploymentType: "deploymentConfigs"

name: admin-console-operator
image:
  name: epamedp/admin-console-operator
  # if not defined then .Chart.AppVersion is used
  version:
imagePullPolicy: "IfNotPresent"
annotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

resources:
  limits:
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi

adminConsole:
  image: "epamedp/edp-admin-console"
  version: "2.12.0-SNAPSHOT"
  imagePullPolicy: "IfNotPresent"
  envs:
    - name: INTEGRATION_STRATEGIES
      value: "Create,Clone,Import"
    - name: BUILD_TOOLS
      value: "maven"
    - name: DEPLOYMENT_SCRIPT
      value: "helm-chart"
    - name: VERSIONING_TYPES
      value: "default,edp"
    - name: CI_TOOLS
      value: "Jenkins,GitLab CI"
    - name: PERF_DATA_SOURCES
      value: "Sonar,Jenkins,GitLab"
  basePath: ""
  imagePullSecrets:
  authKeycloakEnabled: true
  projectUrlMask: "/console/project/{namespace}/overview"
  imageStreamUrlMask: "/console/project/{namespace}/browse/images/{stream}"
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ingress:
    annotations: {}
    # pathType is only for k8s >= 1.1=
    pathType: Prefix
    # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
    # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
    # ingressClassName: nginx
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi
