global:
  edpName: ""
  platform: "openshift"
  dnsWildCard:

name: admin-console-operator
image:
  name: epamedp/admin-console-operator
  version: v2.4.0

adminConsole:
  image: "epamedp/edp-admin-console"
  version: "v2.4.0"
  pullSecrets:

edp:
  version: "v2.4.0"
  db:
    host:
    port: 5432