global:
  edpName: ""
  platform: "openshift"
  dnsWildCard:
  version: "v2.4.0"
  database:
    deploy: true
    host:
    name: "edp-db"
    port: 5432
  webConsole:
    url:


name: admin-console-operator
image:
  name: epamedp/admin-console-operator
  version: v2.4.0

resources:
  limits:
    cpu: 200m
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi

adminConsole:
  image: "epamedp/edp-admin-console"
  version: "2.6.0"
  basePath: ""
  imagePullSecrets:
  authKeycloakEnabled: true
  projectUrlMask: "/console/project/{namespace}/overview"
  imageStreamUrlMask: "/console/project/{namespace}/browse/images/{stream}"
  buildTools: "maven"

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi