name: admin-console-operator
namespace: ""
platform: "openshift"
cdPipelineName: ""
cdPipelineStageName: ""
dnsWildcard: ""
database:
  required: false
ingress:
  required: false
image:
  name: admin-console-operator
  version: latest