global:
  edpName: ""
  platform: "openshift"
  dnsWildCard:
  version: "v2.4.0"
  database:
    host:
    port: 5432

name: admin-console-operator
image:
  name: epamedp/admin-console-operator
  version: v2.4.1

adminConsole:
  image: "epamedp/edp-admin-console"
  version: "v2.4.2"
  basePath: ""
  testReportTools: "Allure"
  imagePullSecrets:
