{{ if eq .Values.global.platform "openshift" }}
apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "admin-console-operator.labels" . | nindent 4 }}
  name: edp-{{ .Values.name }}-{{ .Values.global.edpName }}
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - '*'
  resources:
  - securitycontextconstraints
  verbs:
  - create
  - get
  - list
  - delete
  - update
- apiGroups:
    - '*'
  resources:
    - adminconsoles
    - adminconsoles/finalizers
    - adminconsoles/status
    - keycloaks
    - keycloaks/status
    - keycloakclients
    - keycloakclients/finalizers
    - keycloakclients/status
    - keycloakrealms
    - keycloakrealms/status
    - edpcomponents
  verbs:
    - '*'
{{ end }}
