{{ if eq .Values.platform "kubernetes" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}-{{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edp-{{ .Values.name }}-clusterrole-{{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.name }}-edp"
    namespace: {{ .Values.namespace }}
{{ end }}