{{ if eq .Values.platform "kubernetes" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    annotations:
        openshift.io/description: Role for {{ .Values.name }}-edp service account
        openshift.io/reconcile-protect: "false"
    name: edp-{{ .Values.name }}-clusterrole-{{ .Values.namespace }}
rules:
- apiGroups:
  - '*'
  attributeRestrictions: null
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
    - '*'
  attributeRestrictions: null
  resources:
    - adminconsoles
    - adminconsoles/finalizers
    - adminconsoles/status
    - keycloaks
    - keycloaks/status
    - keycloakclients
    - keycloakclients/finalizers
    - keycloakclients/status
    - keycloakrealms
    - keycloakrealms/status
    - edpcomponents
  verbs:
    - '*'
- apiGroups:
  - 'storage.k8s.io'
  attributeRestrictions: null
  resources:
  - storageclasses
  verbs:
  - get
  - list
- apiGroups:
    - '*'
  attributeRestrictions: null
  resources:
    - clusterrolebindings
    - clusterroles
  verbs:
    - get
    - create
    - delete
{{ end }}