{{ if eq .Values.global.platform "kubernetes" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "admin-console-operator.labels" . | nindent 4 }}
  name: edp-{{ .Values.name }}-{{ .Values.global.edpName }}
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
    - '*'
  resources:
    - adminconsoles
    - adminconsoles/finalizers
    - adminconsoles/status
    - keycloaks
    - keycloaks/status
    - keycloakclients
    - keycloakclients/finalizers
    - keycloakclients/status
    - keycloakrealms
    - keycloakrealms/status
    - edpcomponents
  verbs:
    - '*'
- apiGroups:
  - 'storage.k8s.io'
  resources:
  - storageclasses
  verbs:
  - get
  - list
- apiGroups:
    - '*'
  resources:
    - clusterrolebindings
    - clusterroles
  verbs:
    - get
    - create
    - delete
{{ end }}
