{{ if eq .Values.global.platform "kubernetes" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: admin-console-sc-access
rules:
- apiGroups:
  - 'storage.k8s.io'
  attributeRestrictions: null
  resources:
  - storageclasses
  verbs:
  - get
  - list
{{ end }}