apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.name }}
    spec:
      serviceAccountName: edp
      securityContext:
        runAsUser: 1001
        runAsNonRoot: true
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: {{ .Values.name }}
          # Replace this with the built image name
          image: "{{ .Values.image.name }}:{{ .Values.image.version }}"
          command:
            - {{ .Values.name }}
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "{{ .Values.name }}"
            - name: PLATFORM_TYPE
{{if eq .cdPipelineName "admin-console-operator-master-eks "}}
              value: "kubernetes"
{{end}}
{{else}}
              value: "openshift"
{{end}}