{{ if eq .Values.global.platform "kubernetes" }}
{{- $ingressApiIsStable := eq (include "adminConsole.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "adminConsole.ingress.supportsIngressClassName" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "adminConsole.ingress.supportsPathType" .) "true" -}}
{{- $ingressPathType := .Values.adminConsole.ingress.pathType -}}
kind: Ingress
apiVersion: {{ include "adminConsole.ingress.apiVersion" . }}
metadata:
  name: edp-admin-console
  labels:
    app: edp-admin-console
    {{- include "admin-console-operator.labels" . | nindent 4 }}
  {{- with .Values.adminConsole.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and $ingressSupportsIngressClassName .Values.adminConsole.ingress.ingressClassName }}
  ingressClassName: {{ .Values.adminConsole.ingress.ingressClassName }}
  {{- end }}
{{- if .Values.adminConsole.ingress.tls }}
  tls:
{{ tpl (toYaml .Values.adminConsole.ingress.tls) $ | indent 4 }}
{{- end }}
  rules:
    - host: {{if .Values.adminConsole.basePath}}{{ .Values.global.dnsWildCard }}{{else}}edp-admin-console-{{ .Values.global.edpName }}.{{ .Values.global.dnsWildCard }}{{end}}
      http:
        paths:
          - path: {{if .Values.adminConsole.basePath}}/{{.Values.adminConsole.basePath}}(/|$)(.*){{else}}/{{end}}
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: edp-admin-console
                port:
                  number: 8080
              {{- else }}
              serviceName: edp-admin-console
              servicePort: 8080
              {{- end }}
{{ end }}
