{{ if eq .Values.global.platform "openshift" }}
apiVersion: authorization.openshift.io/v1
kind: Role
metadata:
  name: edp-{{ .Values.name }}-{{ .Values.global.edpName }}
  labels:
    {{- include "admin-console-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - codebases
  - codebasebranches
  - cdpipelines
  - stages
  - codebases/finalizers
  - codebasebranches/finalizers
  - cdpipelines/finalizers
  - stages/finalizers
  verbs:
  - create
  - get
  - delete
  - update
  - patch
{{ end}}
