{{- if eq .Values.global.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: edp-{{ .Values.name }}-{{ .Values.global.edpName }}
  labels:
    {{- include "admin-console-operator.labels" . | nindent 4 }}
roleRef:
  name: edp-{{ .Values.name }}-{{ .Values.global.edpName }}
  namespace: {{ .Values.global.edpName }}
subjects:
  - kind: ServiceAccount
    name: edp-{{ .Values.name }}
    namespace: {{ .Values.global.edpName }}
userNames:
  - system:serviceaccount:{{ .Values.global.edpName }}:edp-{{ .Values.name }}
groupNames: []
{{- end -}}