{{ if eq .Values.global.platform "openshift" }}
apiVersion: authorization.openshift.io/v1
kind: Role
metadata:
  name: edp-{{ .Values.name }}-{{ .Values.global.edpName }}
  labels:
    {{- include "admin-console-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - '*'
  resources:
  - securitycontextconstraints
  verbs:
  - create
  - get
  - list
  - delete
  - update
- apiGroups:
    - '*'
  resources:
    - adminconsoles
    - adminconsoles/finalizers
    - adminconsoles/status
    - keycloaks
    - keycloaks/status
    - keycloakclients
    - keycloakclients/finalizers
    - keycloakclients/status
    - keycloakrealms
    - keycloakrealms/status
    - edpcomponents
    - codebases
    - codebasebranches
    - cdpipelines
    - stages
    - codebases/finalizers
    - codebasebranches/finalizers
    - cdpipelines/finalizers
    - stages/finalizers
  verbs:
    - '*'
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - create
    - get
    - list
    - update
{{ end}}
