{{- if eq .Values.global.platform "kubernetes" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edp-resources-admin
roleRef:
  kind: Role
  name: edp-resources-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: edp-admin-console
    namespace: {{.Values.global.edpName}}
userNames:
  - system:serviceaccount:{{.Values.global.edpName}}:edp-admin-console
{{- end -}}