{{ if eq .Values.global.platform "kubernetes" }}
apiVersion: rbac.authorization.k8s.io/v1
{{else}}
apiVersion: authorization.openshift.io/v1
{{end}}
kind: Role
metadata:
  name: edp-resources-admin
  labels:
    {{- include "admin-console-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - codebases
  - codebasebranches
  - cdpipelines
  - stages
  - codebases/finalizers
  - codebasebranches/finalizers
  - cdpipelines/finalizers
  - stages/finalizers
  - jiraservers
  - jiraservers/finalizers
  verbs:
  - get
  - create
  - update
  - delete
  - patch
  - list
- apiGroups:
  - '*'
  verbs:
  - get
  resources:
  - codebaseimagestreams
- apiGroups:
  - '*'
  verbs:
  - get
  - list
  resources:
  - edpcomponents
