{{ if eq .Values.global.platform "kubernetes" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: edp-admin-console-{{ .Values.global.edpName }}
  labels:
    {{- include "admin-console-operator.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - 'storage.k8s.io'
  resources:
  - storageclasses
  verbs:
  - get
  - list
{{ end }}
