{{ if eq .Values.global.platform "kubernetes" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: edp-{{ .Values.name }}-{{ .Values.global.edpName }}
  labels:
    {{- include "admin-console-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
    - '*'
  resources:
    - codebases
    - codebasebranches
    - cdpipelines
    - stages
    - codebases/finalizers
    - codebasebranches/finalizers
    - cdpipelines/finalizers
    - stages/finalizers
    - adminconsoles
    - adminconsoles/finalizers
    - adminconsoles/status
    - keycloaks
    - keycloaks/status
    - keycloakclients
    - keycloakclients/finalizers
    - keycloakclients/status
    - keycloakrealms
    - keycloakrealms/status
    - edpcomponents
  verbs:
    - '*'
- apiGroups:
  - 'storage.k8s.io'
  resources:
  - storageclasses
  verbs:
  - get
  - list
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - create
    - get
    - list
    - update
{{ end}}
