apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: admin-console-operator
roleRef:
  name: edp-deploy-role
subjects:
  - kind: ServiceAccount
    name: edp
    namespace: {{ .Values.namespace }}
userNames:
  - system:serviceaccount:{{ .Values.namespace }}:edp