{{if and (eq .Values.global.platform "openshift") (eq .Values.global.openshift.deploymentType "deploymentConfigs")}}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: edp-admin-console
    {{- include "admin-console-operator.labels" . | nindent 4 }}
  {{- with .Values.adminConsole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: edp-admin-console
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: edp-admin-console
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: edp-admin-console
    spec:
      {{- if .Values.adminConsole.imagePullSecrets}}
      imagePullSecrets:
        {{- range .Values.adminConsole.imagePullSecrets }}
        - {{. -}}
        {{- end -}}
      {{end}}
      containers:
        - env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
    {{- if .Values.adminConsole.basePath }}
            - name: HOST
              value: "https://{{ .Values.global.dnsWildCard }}/{{ .Values.adminConsole.basePath }}"
            - name: BASE_PATH
              value: "/{{.Values.adminConsole.basePath}}"
    {{- else }}
            - name: HOST
              value: "https://edp-admin-console-{{ .Values.global.edpName}}.{{.Values.global.dnsWildCard }}"
    {{- end }}
            - name: EDP_ADMIN_CONSOLE_VERSION
              value: "{{.Values.adminConsole.version}}"
            - name: EDP_VERSION
              value: "{{.Values.global.version}}"
            - name: AUTH_KEYCLOAK_ENABLED
              value: "false"
            - name: DNS_WILDCARD
              value: "{{.Values.global.dnsWildCard}}"
            - name: OPENSHIFT_CLUSTER_URL
              value: "{{.Values.global.webConsole.url}}"
            - name: DB_ENABLED
              value: "false"
            - name: PLATFORM_TYPE
              value: "openshift"
            - name: VCS_INTEGRATION_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: vcs_integration_enabled
                  name: edp-config
            - name: PROJECT_MASK_URL
              value: "{{.Values.adminConsole.projectUrlMask}}"
            - name: IMAGE_STREAM_MASK_URL
              value: "{{.Values.adminConsole.imageStreamUrlMask}}"
{{ toYaml .Values.adminConsole.envs | indent 12 }}
          image: "{{.Values.adminConsole.image}}:{{.Values.adminConsole.version}}"
          imagePullPolicy: "{{ .Values.adminConsole.imagePullPolicy }}"
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 120
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          name: edp-admin-console
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 20
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          resources:
            requests:
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: edp-admin-console
      serviceAccountName: edp-admin-console
      terminationGracePeriodSeconds: 30
      {{- with .Values.adminConsole.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.adminConsole.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.adminConsole.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  test: false
  triggers:
    - type: ConfigChange
{{end}}
