{{if or (eq .Values.global.platform "kubernetes") (eq .Values.global.openshift.deploymentType "deployments")}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: edp-admin-console
    {{- include "admin-console-operator.labels" . | nindent 4 }}
  {{- with .Values.adminConsole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: edp-admin-console
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: edp-admin-console
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: edp-admin-console
    spec:
      containers:
        - env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: HOST
              value: "https://{{if .Values.adminConsole.basePath}}{{ .Values.global.dnsWildCard }}{{else}}edp-admin-console-{{.Values.global.edpName}}.{{.Values.global.dnsWildCard}}{{end}}{{if .Values.adminConsole.basePath}}/{{.Values.adminConsole.basePath}}{{end}}"
            - name: BASE_PATH
              value: "{{if .Values.adminConsole.basePath}}/{{.Values.adminConsole.basePath}}{{else}}{{end}}"
            - name: EDP_ADMIN_CONSOLE_VERSION
              value: "{{.Values.adminConsole.version}}"
            - name: EDP_VERSION
              value: "{{.Values.global.version}}"
            - name: AUTH_KEYCLOAK_ENABLED
              value: "false"
            - name: DNS_WILDCARD
              value: "{{.Values.global.dnsWildCard}}"
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: db-admin-console
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: db-admin-console
            - name: PLATFORM_TYPE
              value: "kubernetes"
            - name: VCS_INTEGRATION_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: vcs_integration_enabled
                  name: edp-config
            - name: PG_HOST
              value: "{{.Values.global.database.host}}"
            - name: PG_PORT
              value: "{{.Values.global.database.port}}"
            - name: PG_DATABASE
              value: "{{.Values.global.database.name}}"
            - name: DB_ENABLED
              value: "{{.Values.global.database.deploy}}"
            - name: PROJECT_MASK_URL
              value: "{{.Values.adminConsole.projectUrlMask}}"
            - name: IMAGE_STREAM_MASK_URL
              value: "{{.Values.adminConsole.imageStreamUrlMask}}"
{{ toYaml .Values.adminConsole.envs | indent 12 }}
          image: "{{.Values.adminConsole.image}}:{{.Values.adminConsole.version}}"
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 180
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          name: edp-admin-console
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          resources:
{{ toYaml .Values.adminConsole.resources | indent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
      serviceAccount: edp-admin-console
      serviceAccountName: edp-admin-console
      terminationGracePeriodSeconds: 30
      {{- with .Values.adminConsole.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.adminConsole.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.adminConsole.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{end}}
