{{if eq .Values.global.platform "openshift"}}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: edp-admin-console
  name: edp-admin-console
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: edp-admin-console
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: edp-admin-console
    spec:
      {{- if .Values.adminConsole.imagePullSecrets}}
      imagePullSecrets:
        {{- range .Values.adminConsole.imagePullSecrets }}
        - {{. -}}
        {{- end -}}
      {{end}}
      containers:
        - env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: HOST
              value: "https://{{if .Values.adminConsole.basePath}}{{ .Values.global.dnsWildCard }}{{else}}edp-admin-console-{{.Values.global.edpName}}.{{.Values.global.dnsWildCard}}{{end}}{{if .Values.adminConsole.basePath}}/{{.Values.adminConsole.basePath}}{{end}}"
            - name: BASE_PATH
              value: "{{if .Values.adminConsole.basePath}}/{{.Values.adminConsole.basePath}}{{else}}{{end}}"
            - name: EDP_ADMIN_CONSOLE_VERSION
              value: "{{.Values.adminConsole.version}}"
            - name: EDP_VERSION
              value: "{{.Values.global.version}}"
            - name: AUTH_KEYCLOAK_ENABLED
              value: "false"
            - name: DNS_WILDCARD
              value: "{{.Values.global.dnsWildCard}}"
            - name: OPENSHIFT_CLUSTER_URL
              value: "{{.Values.global.webConsole.url}}"
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: db-admin-console
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: db-admin-console
            - name: INTEGRATION_STRATEGIES
              value: "Create,Clone,Import"
            - name: BUILD_TOOLS
              value: "{{.Values.adminConsole.buildTools}}"
            - name: DEPLOYMENT_SCRIPT
              value: "helm-chart,openshift-template"
            - name: PLATFORM_TYPE
              value: "openshift"
            - name: VERSIONING_TYPES
              value: "default,edp"
            - name: CI_TOOLS
              value: "Jenkins,GitLab CI"
            - name: PERF_DATA_SOURCES
              value: "Sonar,Jenkins,GitLab"
            - name: VCS_INTEGRATION_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: vcs_integration_enabled
                  name: edp-config
            - name: EDP_NAME
              valueFrom:
                configMapKeyRef:
                  key: edp_name
                  name: edp-config
            - name: PG_HOST
              value: "{{.Values.global.database.host}}"
            - name: PG_PORT
              value: "{{.Values.global.database.port}}"
            - name: PG_DATABASE
              value: "{{.Values.global.database.name}}"
            - name: DB_ENABLED
              value: "{{.Values.global.database.deploy}}"
            - name: PROJECT_MASK_URL
              value: "{{.Values.adminConsole.projectUrlMask}}"
            - name: IMAGE_STREAM_MASK_URL
              value: "{{.Values.adminConsole.imageStreamUrlMask}}"
          image: "{{.Values.adminConsole.image}}:{{.Values.adminConsole.version}}"
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 180
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          name: edp-admin-console
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          resources:
            requests:
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: edp-admin-console
      serviceAccountName: edp-admin-console
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange
{{end}}
